### PR TITLE
Update iDRAC - Host Stats.json

### LINKED ISSUE #29: BIOS and Service Tag Question
Hello and thank you for your work this is a lifesaver indeed.

Can't see the bios and service tags here:

image

But can see tag here and want to add a column to this:

Screenshot 2023-06-08 at 17 54 18

How to add a column to this table which includes BIOS ınfo?

Thanks in advance.

### LINKED ISSUE #35: Angular Deprecated - Panels need to be updated
Panels need to be upgraded to stay compatible with Grafana 11, i issued a pull request to meet the new requirements

### PR DESCRIPTION
**Pull request by bgatestmg**
Updated panels to support grafana 11 and the angular deprecation

### CODE REVIEW

**Review by ilovepancakes95 — CHANGES_REQUESTED** [review]
Looks good and works well mostly. Commented on a few sections to correct some minor errors that weren't displaying correctly. If you want to implement them in, I'll then merge your commit. There are a couple other display issues I noticed (OS info not showing on some iDRACs, NIC status missing on some machines, etc.) but I think those are more issues specific to my setup or database somehow than the dashboard. Curious if all panels display data for you or if you have some minor issues too with missing info....

Thanks for the help getting this updated to work with Grafana v11.

**Comment by bgatestmg** [comment]
> Looks good and works well mostly. Commented on a few sections to correct some minor errors that weren't displaying correctly. If you want to implement them in, I'll then merge your commit. There are a couple other display issues I noticed (OS info not showing on some iDRACs, NIC status missing on some machines, etc.) but I think those are more issues specific to my setup or database somehow than the dashboard. Curious if all panels display data for you or if you have some minor issues too with missing info....
> 
> Thanks for the help getting this updated to work with Grafana v11.

All panels are working appropriately on my end. OS Info, NIC Status etc it is likely a slight difference in idrac versions, ill go ahead and implement the modifications requested

**Comment by bgatestmg** [comment]
edits have been made, i believe i merged them in

**Comment by bgatestmg** [comment]
had one more small change, had to select sharing for external

**Comment by ilovepancakes95** [comment]
Thanks, when you are exporting, are you checking the option to "Export for use externally"? It seems this latest json still has install specific data in it rather than being a generic version.

Also, per your other comment, out of curiosity, what versions of iDRAC are you using with this dashboard?

**Review by ilovepancakes95 — APPROVED** [review]

**Comment by ilovepancakes95** [comment]
> All panels are working appropriately on my end. OS Info, NIC Status etc it is likely a slight difference in idrac versions, ill go ahead and implement the modifications requested

Which iDRAC versions do you use with this dashboard?

**Comment by ilovepancakes95** [comment]
Merged, thanks again for the contribution!

**Comment by bgatestmg** [comment]
idrac 8 and 9 mostly we have a single idrac7 server, and happy to help!


> > All panels are working appropriately on my end. OS Info, NIC Status etc it is likely a slight difference in idrac versions, ill go ahead and implement the modifications requested
> 
> Which iDRAC versions do you use with this dashboard?

**Comment by ilovepancakes95** [comment]
> idrac 8 and 9 mostly we have a single idrac7 server

Ahh okay, I am using 7 and 8. The 7 seems to be missing NIC status data (connected/not connected) and the 8 ones seem to all have it. Also missing OS info on one of the 8's but it works on another (and they both have the same OS) so no idea what is going on there.

**Comment by bgatestmg** [comment]
I noticed the OS info isn’t showing on one of our servers that runs Windows Server 2019, but the rest running ESXi show no issues.

From: ilovepancakes95 ***@***.***>
Date: Monday, May 20, 2024 at 2:11 PM
To: ilovepancakes95/idrac_snmp-grafana ***@***.***>
Cc: Brian Gates ***@***.***>, Author ***@***.***>
Subject: Re: [ilovepancakes95/idrac_snmp-grafana] Update iDRAC - Host Stats.json (PR #34)

idrac 8 and 9 mostly we have a single idrac7 server

Ahh okay, I am using 7 and 8. The 7 seems to be missing NIC status data (connected/not connected) and the 8 ones seem to all have it. Also missing OS info on one of the 8's but it works on another (and they both have the same OS) so no idea what is going on there.

**Comment by ilovepancakes95** [comment]
> I noticed the OS info isn’t showing on one of our servers that runs Windows Server 2019, but the rest running ESXi show no issues.

Just logged into iDRAC directly on that one machine and the OS info doesn't even display there so must be something on Dell's end. What is weird is I have an exact copy of this machine (same model, same BIOS, same hardware, same OS (ESXi)) and the OS info does show for that.

**Comment by bgatestmg** [comment]
That’s definitely strange, gotta love dells quirkiness eh

From: ilovepancakes95 ***@***.***>
Date: Monday, May 20, 2024 at 2:19 PM
To: ilovepancakes95/idrac_snmp-grafana ***@***.***>
Cc: Brian Gates ***@***.***>, Author ***@***.***>
Subject: Re: [ilovepancakes95/idrac_snmp-grafana] Update iDRAC - Host Stats.json (PR #34)

I noticed the OS info isn’t showing on one of our servers that runs Windows Server 2019, but the rest running ESXi show no issues.

Just logged into iDRAC directly on that one machine and the OS info doesn't even display there so must be something on Dell's end. What is weird is I have an exact copy of this machine (same model, same BIOS, same hardware, same OS (ESXi)) and the OS info does show for that.

**Pull request merged**
